### PR TITLE
Mysqli migration

### PR DESCRIPTION
**Pull request by stmeissner**
I've migrated from mysql to mysqli in its procedural form.
It is not very nice and only a small step towards more security as reported in #1, but better than before.

### CODE REVIEW

**Comment by avs-code** [comment]
I was testing it and get this errors seeing the upload file section and creating a team:

```
Warning: mysqli_query() expects parameter 1 to be mysqli, null given in /home/u275158832/public_html/prem/upload.php on line 104
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, null given in /home/u275158832/public_html/prem/upload.php on line 105
Parse error: syntax error, unexpected '(' in /home/u275158832/public_html/prem/team_add_do.php on line 44
```

**Comment by stmeissner** [comment]
double post, plz see other comment

**Comment by stmeissner** [comment]
@arv187 I fixed the bug with creating a new team. Thanks for testing it.
Regarding uploading files, the error does not occur anymore now, but the uploaded file is not stored in the data base of my test system, only on the file system. But it also doesn't work on current master branch before my changes.
Has it ever worked for you?

**Comment by avs-code** [comment]
Uploads is working fine for me, with previous version and with your modified files. The file is uploaded to "uploads" folder and registered in "uploads" table in db.

May be a php/mysql version or config?

php 5.6.35-81.0 - Percona Server (GPL), Release 81.0, Revision c96c427
Apache/2.2.15 (CentOS)
libmysql - 5.1.73
PHP: mysqli

let me know if I already merge or you want to check uploads.

**Comment by stmeissner** [comment]
Yes, might be a problem with my config, good that it's working on your environment.
Feel free to merge, you are the project owner :)

**Comment by avs-code** [comment]
In fact all the collaborators are owners/authors xD
Im just the project administrator.
So I am grateful that the people who collaborate bring their changes and improvements here.
Thanks @stmeissner for your work.

**Review by avs-code — COMMENTED** [review]
All right

**Pull request merged**
